// Shared blog post metadata — single source of truth for the blog index
// and the RelatedPosts component. Keep in sync with src/app/blog/<slug>/page.js.
export const posts = [
  {
    slug: 'roof-replacement-cost-dallas-ga',
    title: 'Roof Replacement Cost in Dallas, GA: Planning Factors (Not a Quote)',
    date: 'September 2026',
    excerpt: 'What drives roof replacement cost in Dallas, GA — squares, pitch, materials, decking, tear-off. No prices published; you get a written figure after a free inspection.',
    readTime: '7 min read',
    category: 'Cost Guide',
  },
  {
    slug: 'roof-repair-cost-dallas-ga',
    title: 'Roof Repair Cost in Dallas, GA: Planning Factors (Not a Quote)',
    date: 'October 2026',
    excerpt: 'What changes roof repair cost in Dallas, GA — leak source, access, materials, storm path. No prices published; you get a written figure after a free inspection.',
    readTime: '6 min read',
    category: 'Cost Guide',
  },
  {
    slug: 'solar-panels-roof-dallas-ga',
    title: 'Solar Panels on Your Dallas Roof: What Homeowners Need to Know Before Installing',
    date: 'August 2026',
    excerpt: 'Panels sit on your roof for decades. Why the roof should come first, the flashing details that prevent leaks, and who warrants what when solar and roofing meet.',
    readTime: '5 min read',
    category: 'Homeowner Guide',
  },
  {
    slug: 'roof-maintenance-calendar-dallas-ga',
    title: 'Year-Round Roof Maintenance Calendar for Dallas GA Homeowners',
    date: 'July 2026',
    excerpt: 'Spring hail, summer UV, fall leaves, winter ice — each attacks your roof differently. A quarterly routine catches the small stuff before it becomes a full replacement conversation. Here is your seasonal checklist.',
    readTime: '7 min read',
    category: 'Maintenance',
  },
  {
    slug: 'skylight-leak-repair-dallas-ga',
    title: 'Skylight Leak Repair in Dallas GA: Why They Leak, How We Fix Them, and When to Replace',
    date: 'July 2026',
    excerpt: 'Skylights are a common source of roof leaks in Dallas homes. Why they fail, how to tell a leak from condensation, and when to repair vs. replace.',
    readTime: '6 min read',
    category: 'Repairs',
  },
  {
    slug: 'how-to-choose-roofing-contractor-dallas-ga',
    title: 'How to Choose a Roofing Contractor in Dallas GA: 7 Red Flags & 5 Must-Ask Questions',
    date: 'June 2026',
    excerpt: 'After every major storm, out-of-state storm chasers flood Dallas neighborhoods. How to tell pros from chasers: 7 red flags, 5 must-ask questions, and what to verify before you hire.',
    readTime: '8 min read',
    category: 'Homeowner Guide',
  },
  {
    slug: 'roof-financing-options-dallas-ga',
    title: 'Roof Financing Options in Dallas GA: How to Pay for a New Roof Without Breaking the Bank',
    date: 'June 2026',
    excerpt: 'Most homeowners don’t have a full replacement sitting in savings. Insurance paths, lender financing, personal loans and HELOCs — ask for current terms on your estimate.',
    readTime: '7 min read',
    category: 'Cost Guide',
  },
  {
    slug: 'georgia-hail-storm-roof-checklist',
    title: 'Hail Damage on Your Georgia Roof: What It Looks Like and What to Do (6 Steps)',
    date: 'October 2025',
    excerpt: 'Hail damage is easy to miss from the ground. What bruised shingles and dented soft metals look like, a six-step checklist for the days after a storm, and how to choose a roofer.',
    readTime: '6 min read',
    category: 'Storm Damage',
  },
  {
    slug: 'when-to-replace-vs-repair-a-roof',
    title: 'Roof Repair vs. Replacement: How to Tell Which Your Roof Needs',
    date: 'November 2025',
    excerpt: 'Repair or replace? The signs that point each way, why a ceiling stain rarely sits under the leak, and how roof age and storm damage factor into the decision.',
    readTime: '6 min read',
    category: 'Maintenance',
  },
  {
    slug: 'choosing-roofing-materials-dallas-ga',
    title: 'How to Choose the Right Roofing Material for Your Dallas Home',
    date: 'November 2025',
    excerpt: 'Asphalt, metal, slate, or tile — each handles Dallas heat, hail, and storms differently. Here is our guide to choosing the right material based on budget, timeline, and home style.',
    readTime: '5 min read',
    category: 'Materials',
  },
  {
    slug: 'dallas-ga-hail-storm-insurance-claims',
    title: 'Dallas, GA Hail Damage: How to Document and File a Roof Insurance Claim',
    date: 'December 2025',
    excerpt: 'How to document hail damage, work with your adjuster, understand your wind/hail deductible, and what to do if the first estimate looks short.',
    readTime: '7 min read',
    category: 'Storm Damage',
  },
  {
    slug: 'gutter-maintenance-dallas-ga',
    title: 'Gutters in Dallas GA: How Often to Clean, When to Replace, and Why It Matters for Your Roof',
    date: 'December 2025',
    excerpt: 'Clogged gutters send water into fascia, roof edges and foundations. Here’s how often to clean them in North Georgia, and when to repair vs. replace.',
    readTime: '6 min read',
    category: 'Maintenance',
  },
  {
    slug: 'attic-ventilation-dallas-heat',
    title: 'Why Your Attic Is So Hot in Dallas Summers (and What Ventilation Fixes)',
    date: 'January 2026',
    excerpt: 'A hot attic bakes shingles from below and makes upstairs rooms hard to cool. How ridge vents, soffit intake and exhaust fans work together, and the signs your attic needs help.',
    readTime: '5 min read',
    category: 'Maintenance',
  },
  {
    slug: 'new-construction-roofing-dallas',
    title: 'New Construction Roofing in Dallas GA: What Builders Need to Know',
    date: 'January 2026',
    excerpt: 'From permit requirements to shingle selection to warranty coordination — a checklist for builders installing roofs on new Dallas homes.',
    readTime: '5 min read',
    category: 'New Construction',
  },
  {
    slug: 'cost-of-new-roof-2026-dallas-ga',
    title: 'What a New Roof Costs in Dallas, GA: The Factors That Set the Price',
    date: 'February 2026',
    excerpt: 'Size, pitch, layers, decking, materials and access — the factors that move the price of a new roof in Dallas, GA, and how to get a written figure after a free inspection.',
    readTime: '6 min read',
    category: 'Cost Guide',
  },
  {
    slug: 'architectural-vs-3-tab-shingles',
    title: 'Architectural vs. 3-Tab Shingles: What Actually Changes for Dallas Homes',
    date: 'February 2026',
    excerpt: "The difference between architectural and 3-tab shingles is more than price — it's lifespan, warranty, and how your insurance claim gets paid.",
    readTime: '7 min read',
    category: 'Materials',
  },
  {
    slug: 'wind-damage-roof-repair-dallas',
    title: 'Wind Damage on Your Roof: How to Spot It Before the Next Storm Hits',
    date: 'March 2026',
    excerpt: "Georgia storms bring strong wind gusts. Here's what wind does to a roof, what to check safely from the ground, and when to call for repair.",
    readTime: '6 min read',
    category: 'Storm Damage',
  },
  {
    slug: 'emergency-roof-tarping-dallas',
    title: 'Emergency Roof Tarping: What to Expect When We Come to Your Dallas Home',
    date: 'March 2026',
    excerpt: 'When a storm rips off shingles and rain is coming, an emergency tarp limits the damage. Here’s what our crew does, what to do while you wait, and how insurance fits in.',
    readTime: '5 min read',
    category: 'Emergency',
  },
  {
    slug: 'emergency-roof-response-time-dallas',
    title: 'Emergency Roof Response: What Affects How Fast a Crew Arrives',
    date: 'May 2026',
    excerpt: 'When a storm hits, response time matters. What affects how fast a crew can reach you in the Dallas area, and how to help us get there sooner.',
    readTime: '5 min read',
    category: 'Emergency',
  },
  {
    slug: 'metal-roofing-pros-cons-dallas',
    title: 'Metal Roofing in Dallas: The Pros, Cons and Trade-Offs',
    date: 'April 2026',
    excerpt: 'Metal roofs last a long time and handle wind well, but they cost more up front and repair differently. An honest look at the pros, cons and insurance questions.',
    readTime: '6 min read',
    category: 'Materials',
  },
  {
    slug: 'georgia-winter-roof-inspection',
    title: 'Georgia Winter Roof Prep: The 10-Point Checklist Before the Cold Hits',
    date: 'April 2026',
    excerpt: 'Georgia winters are mild, but freezing rain, freeze-thaw cycles and leaks left from summer storms still find weak spots. Here’s what to check before the cold sets in.',
    readTime: '6 min read',
    category: 'Maintenance',
  },
  {
    slug: 'roof-warranty-what-is-covered',
    title: 'Roof Warranty Explained: What’s Covered (Manufacturer vs Workmanship)',
    date: 'May 2026',
    excerpt: 'Manufacturer vs. workmanship roof warranties — what they cover, what they don’t, and how to get help in Dallas, GA.',
    readTime: '8 min read',
    category: 'Warranty',
  },
];
